server:
  port: 8080
  servlet:
    context-path: /restapidemo

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aws-test.cx4sekbx7rdu.us-east-1.rds.amazonaws.com:3306/restapiDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: P1234567q